// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrxsmrgelksqxjvfyvue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyeHNtcmdlbGtzcXhqdmZ5dnVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNzQ2NjgsImV4cCI6MjA1OTg1MDY2OH0.mnSf3voJKCHe6dQVcPlpXT4nHD7-4qtwRJTjk4NAiRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);